#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

printf "\n--> Running Rubocop all...\n"
bin/run_rubocop

printf "\n--> Running ShellSpec...\n"
bin/run_shellspec

printf "\n--> Running RSpec...\n"
bundle exec rspec
