#!/usr/bin/env bash
set -euo pipefail
if [[ ${SET_X:-} ]]; then
  set -x
fi
IFS=$'\n\t'

SKIP=no-commit-to-branch pre-commit run --config ~/.pre-commit-config.yml || exit

# TODO: This works on the working copy, check https://stackoverflow.com/a/3068990/372654 and https://pre-commit.com/
mapfile -t files < <(git diff --name-only --cached --diff-filter=ACMR) # cSpell:ignore ACMR

printf 'RuboCop: '
"$DOTFILES_SHARED"/bin/run_rubocop "${files[@]}" && echo '✅' || exit

printf 'ShellCheck: '
bin/run_shellcheck.rb "${files[@]}" && echo '✅' || exit
