#!/usr/bin/env bash

# https://github.com/asdf-community/asdf-direnv#global-asdf-direnv-integration
if command -v asdf >/dev/null 2>&1; then
  # shellcheck disable=SC1090
  . "$(asdf direnv hook asdf)"
fi
