# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
window:
  dimensions:
    columns: 150
    lines: 50

option_as_alt: Both

font:
  normal:
    family: CaskaydiaCove NF
    style: Regular
  bold:
    family: CaskaydiaCove NF
    style: Bold
  italic:
    family: CaskaydiaCove NF
    style: Italic
  size: 13.0

# https://github.com/alacritty/alacritty/wiki/Color-schemes
# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xcaa9fa'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'

  # Bright colors
  bright:
    black:   '0x575b70'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'
