on: push

permissions:
  contents: read

jobs:
  ruby:
    name: Ruby
    runs-on: ubuntu-slim
    strategy:
      matrix:
        ruby-version: ['4.0', '3.4']
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run Rubocop
        if: ${{ matrix.ruby-version == '4.0' }}
        run: bundle exec rubocop
      - name: Run RSpec
        run: bundle exec rspec

  # https://github.com/marketplace/actions/shellcheck
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Run ShellCheck
        # cSpell:ignore ludeeus
        uses: ludeeus/action-shellcheck@master
        env:
          # See also: the notes in .shellcheckrc
          SHELLCHECK_OPTS: -s bash
        with:
          ignore_paths: "**/.p10k*.zsh"

  # https://github.com/shellspec/shellspec

  shellspec:
    name: ShellSpec
    runs-on: ubuntu-slim
    strategy:
      matrix:
        shell: ['BASH', 'ZSH']
    steps:
      - uses: actions/checkout@v6

      - name: Install ShellSpec
        run: |
          curl -fsSL https://git.io/shellspec | sh -s latest.tar.gz --bin /usr/local/bin --yes
          echo "ShellSpec version: $(shellspec --version)"

      - name: Install Zsh
        run: |
          # https://github.com/actions/runner-images/issues/10977#issuecomment-2810713336
          # Skip installing package docs (makes the man-db trigger much faster)
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF

          sudo apt-get update -qq
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -qq -y zsh
        if: ${{ matrix.shell == 'ZSH' }}

      - name: Set environment variables
        run: |
          echo "TMPDIR=$RUNNER_TEMP" >> "$GITHUB_ENV"

      - name: Run ShellSpec
        run: ${{ matrix.shell }}_ONLY=1 bin/run_shellspec
